import { Currency } from './index';

export const currencyByRupee: Currency[] = [
    { name: 'DOLLAR', value: 0.012271428, flag: '🇺🇸', symbol: '$' },
    { name: 'EURO', value: 0.01125809, flag: '🇪🇺', symbol: '€' },
    { name: 'POUND', value: 0.0099194378, flag: '🇬🇧', symbol: '£' },
    { name: 'RUBEL', value: 0.85040469, flag: '🇷🇺', symbol: '₽' },
    { name: 'AUS DOLLAR', value: 0.01732574, flag: '🇦🇺', symbol: 'A$' },
    { name: 'CAN DOLLAR', value: 0.016457908, flag: '🇨🇦', symbol: 'C$' },
    { name: 'YEN', value: 1.5909089, flag: '🇯🇵', symbol: '¥' },
    { name: 'DINAR', value: 0.0037446993, flag: '🇰🇼', symbol: 'KD' },
    { name: 'BITCOIN', value: 0.000000543544886, flag: '🎰', symbol: '₿' },
    { name: 'SWISS FRANC', value: 0.011059, flag: '🇨🇭', symbol: 'CHF' },
    { name: 'SINGAPORE DOLLAR', value: 0.01648, flag: '🇸🇬', symbol: 'S$' },
    { name: 'HONG KONG DOLLAR', value: 0.0956, flag: '🇭🇰', symbol: 'HK$' },
    { name: 'NEW ZEALAND DOLLAR', value: 0.01814, flag: '🇳🇿', symbol: 'NZ$' },
    { name: 'SOUTH KOREAN WON', value: 16.23, flag: '🇰🇷', symbol: '₩' },
    { name: 'UAE DIRHAM', value: 0.045, flag: '🇦🇪', symbol: 'AED' },
    { name: 'SAUDI RIYAL', value: 0.046, flag: '🇸🇦', symbol: 'SAR' },
    { name: 'THAI BAHT', value: 0.44, flag: '🇹🇭', symbol: '฿' },
    { name: 'MALAYSIAN RINGGIT', value: 0.056, flag: '🇲🇾', symbol: 'RM' },
    { name: 'BRAZILIAN REAL', value: 0.061, flag: '🇧🇷', symbol: 'R$' },
    { name: 'SOUTH AFRICAN RAND', value: 0.23, flag: '🇿🇦', symbol: 'R' },
    { name: 'MEXICAN PESO', value: 0.22, flag: '🇲🇽', symbol: 'MX$' },
    { name: 'TURKISH LIRA', value: 0.35, flag: '🇹🇷', symbol: '₺' },
    { name: 'PHILIPPINE PESO', value: 0.69, flag: '🇵🇭', symbol: '₱' },
    { name: 'EGYPTIAN POUND', value: 0.38, flag: '🇪🇬', symbol: 'E£' },
    { name: 'ARGENTINE PESO', value: 9.35, flag: '🇦🇷', symbol: 'ARS' },
    { name: 'CHILEAN PESO', value: 10.45, flag: '🇨🇱', symbol: 'CLP$' },
    { name: 'COLOMBIAN PESO', value: 48.35, flag: '🇨🇴', symbol: 'COP$' },
    { name: 'VIETNAMESE DONG', value: 293.5, flag: '🇻🇳', symbol: '₫' },
    { name: 'INDONESIAN RUPIAH', value: 191.2, flag: '🇮🇩', symbol: 'Rp' },
    { name: 'NIGERIAN NAIRA', value: 9.84, flag: '🇳🇬', symbol: '₦' },
    { name: 'BANGLADESHI TAKA', value: 1.35, flag: '🇧🇩', symbol: '৳' },
    { name: 'SRI LANKAN RUPEE', value: 4.08, flag: '🇱🇰', symbol: 'Rs' },
    { name: 'NEPALESE RUPEE', value: 1.60, flag: '🇳🇵', symbol: 'Rs' },
    { name: 'ETHIOPIAN BIRR', value: 0.68, flag: '🇪🇹', symbol: 'Br' },
    { name: 'KENYAN SHILLING', value: 1.41, flag: '🇰🇪', symbol: 'KSh' },
    { name: 'GHANAIAN CEDI', value: 0.14, flag: '🇬🇭', symbol: '₵' },
    { name: 'PERUVIAN SOL', value: 0.045, flag: '🇵🇪', symbol: 'S/.' },
    { name: 'CUBAN PESO', value: 0.30, flag: '🇨🇺', symbol: 'CUP$' },
    { name: 'CZECH KORUNA', value: 0.28, flag: '🇨🇿', symbol: 'Kč' },
    { name: 'HUNGARIAN FORINT', value: 4.10, flag: '🇭🇺', symbol: 'Ft' },
    { name: 'POLISH ZLOTY', value: 0.048, flag: '🇵🇱', symbol: 'zł' },
    { name: 'ROMANIAN LEU', value: 0.056, flag: '🇷🇴', symbol: 'lei' },
    { name: 'BOLIVIAN BOLIVIANO', value: 0.085, flag: '🇧🇴', symbol: 'Bs.' },
    { name: 'PARAGUAYAN GUARANI', value: 84.5, flag: '🇵🇾', symbol: '₲' },
    { name: 'GUATEMALAN QUETZAL', value: 0.093, flag: '🇬🇹', symbol: 'Q' },
    { name: 'UZBEKISTAN SOM', value: 145.2, flag: '🇺🇿', symbol: 'soʻm' },
    { name: 'MYANMAR KYAT', value: 25.6, flag: '🇲🇲', symbol: 'K' },
    { name: 'IRANIAN RIAL', value: 513.8, flag: '🇮🇷', symbol: '﷼' },
];
